### ISSUE TITLE
Cannot upload PDF to wiki

### ISSUE THREAD

**Issue by cxrodgers** [wehr-lab/autopilot#127]
When I try to upload a PDF as the "Datasheet" for something on the wiki, after clicking submit the page reloads with the following error message in red text next to the offending PDF:
  
`must have the correct URL format, starting with "http"`

**Comment by cxrodgers** [comment]
Thanks for the explanation! I think I get it! Feel free to convert to discussion or whatever you think best

**Comment by sneakers-the-rat** [comment]
Closing since the wiki now has a separate field for a url-based datasheet, but keeping this in mind as a source of documentation for the wiki
