### ISSUE TITLE
ZMQ Error

### ISSUE THREAD

**Issue by skeltoh** [wehr-lab/autopilot#140]
When I go to start an autopilot pilot, it starts and says:

`fatal: not a git repository (or any of the parent directories): .git`
`fatal: not a git repository (or any of the parent directories): .git`

Followed by the splash screen. Followed by:

> Process Pilot_Station-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
>     self.run()
>   File "/home/pi/git/autopilot/autopilot/networking/station.py", line 173, in run
>     self.listener.setsockopt_string(zmq.IDENTITY, self.id)
>   File "/home/pi/.venv/autopilot/lib/python3.7/site-packages/zmq/sugar/socket.py", line 340, in set_string
>     return self.set(option, optval.encode(encoding))
>   File "zmq/backend/cython/socket.pyx", line 420, in zmq.backend.cython.socket.Socket.set
>   File "zmq/backend/cython/socket.pyx", line 277, in zmq.backend.cython.socket._setsockopt
>   File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
>   zmq.error.ZMQError: Invalid argument

The process doesn't terminate, it stays there, but it doesn't connect to the terminal, which I'm assuming is due to the last error.

It looks like self.id is set to an empty string in station.py. Did I need to set the local Pilot IP somewhere?

**Comment by sneakers-the-rat** [comment]
yes I think so. alternatively there's no real reason they can't be the same port. inverting the number would require an extension to the notion of constraints in the prefs defaults, to be able to change value depending on another prefs value, but that shouldn't be too hard
