### ISSUE TITLE
Changes for new pi installs- libzmq-dev and https:// instead of git://

### ISSUE THREAD

**Issue by Rowanon** [wehr-lab/autopilot#163]
I have 2 notes on things that updated, with the caveat that I'm extremely new to this and could be missing things.

First, when you're installing the dependencies, libzmq-dev seems to have been renamed libzmq3-dev. Haven't gotten far enough to find out if there are significant changes in it that will break things down the line.

Second, jackd installation failed because apparently using git:// doesn't work anymore and the source should be changed to https://github.com/jackaudio/jack2 instead. For now, running this

git config --global url."https://".insteadOf git:// 

before running the autopilot setup seems to have worked.

**Comment by sneakers-the-rat** [comment]
Awesome, thanks!!! updated those here: https://github.com/wehr-lab/autopilot/commit/90956187d4222f16f67ab8b39b8359da954d5dcc
