### ISSUE TITLE
[new feature] add Tritone as a sound; add highpass filter as a param to Noise

### ISSUE THREAD

**Issue by Rodgers-PAC-Lab** [wehr-lab/autopilot#165]
I'm working on this in my own fork, just wanted to give a heads-up that I might submit a PR, and also welcoming feedback/suggestions. Basically we are doing two things:
* Adding an unpleasant sounding tritone to serve as a (very weak) punishment
* Adding a parameter to highpass filter broadband noise before playing it (because a grant reviewer wanted us to do this)

This is the diff in my fork:
https://github.com/Rodgers-PAC-Lab/autopilot/compare/main...tritone

Will do some additional bug-testing here first and then submit a PR. Please let me know if anyone has suggestions / feedback before then

**Comment by sneakers-the-rat** [comment]
let's continue discussion in the PR :)
