### ISSUE TITLE
system requirements

### ISSUE THREAD

**Issue by mikewehr** [wehr-lab/autopilot#42]
There should be a document that explains the system requirements - do I need a Raspberry Pi 4? Does it have to run Debbian? Can I install the terminal on my Mac or Windows computer or does it have to be linux? Could I install a pilot on a Mac? Etc.
Maybe this should be a paragraph in Readme.md. 
For example I thought this might be described in one of the requirements txt files but those are clearly a different thing.

**Comment by sneakers-the-rat** [comment]
This is currently documented here:
https://docs.auto-pi-lot.com/en/latest/guide.installation.html#supported-systems
in the package metadata:
https://github.com/wehr-lab/autopilot/blob/f2e15fa96099d43907f27d8ae28b5fdeafe95065/setup.py#L139-L143
and in the badges at the top of README.md

I've made that a bit more explicit in this commit: https://github.com/wehr-lab/autopilot/commit/ce0ddf78b7f59f5487fec2ca7e8fb3c0ad162051
