### ISSUE TITLE
No sound while running

### ISSUE THREAD

**Issue by lucasogit** [wehr-lab/autopilot#47]
At some point during running box 6, 7, 8, and 0 all stopped playing white noise.

Logs:
[nosound12_2_20.txt](https://github.com/wehr-lab/autopilot/files/5633415/nosound12_2_20.txt)
[pilot_logs (1).tar.gz](https://github.com/wehr-lab/autopilot/files/5633416/pilot_logs.1.tar.gz)

**Comment by sneakers-the-rat** [comment]
same as https://github.com/wehr-lab/autopilot/issues/41

pis need to be updated

`parallel-ssh -h ~/pi_ips.txt "cd ~/git/autopilot && git pull"`
