### ISSUE TITLE
No sound on box 4

### ISSUE THREAD

**Issue by lucasogit** [wehr-lab/autopilot#65]
After taking mice out after running on gap_laser protocol for 1 hour I noticed box 4 had stopped playing white noise at some point while running. I've had this happen with other boxes and with other protocols before too.

Logs:
[no_sound_box4.txt](https://github.com/wehr-lab/autopilot/files/5923280/no_sound_box4.txt)
[pilot_logs.tar.gz](https://github.com/wehr-lab/autopilot/files/5923281/pilot_logs.tar.gz)

**Comment by sneakers-the-rat** [comment]
still the same conflict between jack from apt and jack from source. local problem, fixing now.
